kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  
  # Nodepool A - hardware=low
  - role: worker
    extraPortMappings: []
    labels:
      hardware: "low"

  - role: worker
    extraPortMappings: []
    labels:
      hardware: "low"

  - role: worker
    extraPortMappings: []
    labels:
      hardware: "low"

  # Nodepool B - hardware=high
  - role: worker
    extraPortMappings: []
    labels:
      hardware: "high"

  - role: worker
    extraPortMappings: []
    labels:
      hardware: "high"
