apiVersion: v1
kind: PersistentVolume
metadata:
  name: sc-pv-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 250Mi
  local:
    path: /pods
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - s2-node-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-data
