apiVersion: v1
kind: Service
metadata:
  name: app-esr2-service
spec:
  type: NodePort
  selector:
    app: app-esr2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
