apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
  persistentVolumeReclaimPolicy: Retain
