apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-manual2
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
