apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-manual2
