apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-meu-wordpress-mariadb-0
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-mariadb
