apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-esr
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-esr
  template:
    metadata:
      labels:
        app: app-esr
    spec:
      containers:
      - name: app-esr
        image: marcelomoreno/app-esr:v2
        ports:
        - containerPort: 5000
        # Adicione limites de recursos (opcional, mas altamente recomendado!)
        resources:
          limits:
            memory: "256Mi" # Limite máximo de memória para o contêiner
            cpu: "500m"    # Limite máximo de CPU (500m = 0.5 core de CPU)
          requests:
            memory: "128Mi" # Requisição mínima de memória
            cpu: "250m"    # Requisição mínima de CPU