apiVersion: v1
kind: Service
metadata:
  name: app-esr-service
spec:
  type: NodePort
  selector:
    app: app-esr
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
