apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: private-registry
spec:
  selector:
    app: private-registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
