apiVersion: v1
kind: Service
metadata:
  name: nginx2-service
spec:
  type: NodePort
  selector:
    app: nginx2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30036  # pode mudar dependendo do cluster, deixe fixo para facilitar acesso externo
